### ISSUE TITLE
Page type is not inferred from a directory name

### ISSUE THREAD

**Issue by EmilySeville7cfg** [526avijitgupta/gokarna#94]
Hugo [docs](https://gohugo.io/content-management/organization/#organization-of-content-source) says:

> While Hugo supports content nested at any level, the top levels (i.e. content/<DIRECTORIES>) are special in Hugo and are considered the content type used to determine layouts etc. To read more about sections, including how to nest them, see [sections](https://gohugo.io/content-management/sections/).

While it is not supported: page type must be specified in the front matter which is a bit confusing.

> This theme supports two types of content types: post and page. To specify them, you need to add them in your markdown metadata.

**Comment by EmilySeville7cfg** [comment]
Please correct me if I am mistaken. 😄

**Comment by yashmehrotra** [comment]
@EmilySeville7cfg 
> Please correct me if I am mistaken

No, your reasoning is correct.

The reason we use a `type` attribute is to give users the freedom to categorize non-blog pages the way they see fit.

Consider an example where the user wants to post blogs, travel diaries, a projects page and an about me page. Since blog posts and travel diaries need to be treated as `post` (have an index and a publish date mainly), but the projects page and about me should be `page` type.

In this instance, the directory name inference would not work as everything under posts would be grouped together (there is a workaround for this but that involves creating a complex sub-directory structure) and another point is to provide a natural URLs ie. `example.com/posts`, `example.com/about`, `example.com/travel` compared to `example.com/pages/about` and `example.com/posts/travel`. (A workaround for this is also present where you can add the `slug` attribute in the markdown but you have to do that for each and every post)

Since the outcome in both cases is the same, we went for end-user simplicity.
